import { NextRequest, NextResponse } from "next/server";
import { Resend } from "resend";
import { createClient } from "@/lib/supabase/server";
import type { Clause, ScanResult } from "@/lib/scan-utils";

function scoreGrade(score: number): string {
  if (score <= 20) return "A";
  if (score <= 40) return "B";
  if (score <= 60) return "C";
  if (score <= 80) return "D";
  return "F";
}

export async function POST(req: NextRequest) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    return NextResponse.json({ error: "Unauthorised" }, { status: 401 });
  }

  const { scan, contractTitle }: { scan: ScanResult; contractTitle: string } = await req.json();

  const topClauses: Clause[] = scan.clauses
    .filter((c) => c.severity === "high")
    .slice(0, 3);

  const grade = scoreGrade(scan.risk_score);
  const scoreColor =
    scan.risk_score <= 29 ? "#4ade80" : scan.risk_score <= 69 ? "#fbbf24" : "#f87171";

  const clauseHtml = topClauses.length > 0
    ? topClauses.map((c, i) => `
        <div style="margin-bottom:16px;padding:14px;background:#fff8f8;border-left:3px solid #f87171;border-radius:6px;">
          <p style="font-size:11px;font-weight:600;color:#dc2626;text-transform:uppercase;margin:0 0 6px;">
            HIGH RISK · ${c.category.replace(/_/g, " ").toUpperCase()} · #${i + 1}
          </p>
          <p style="font-size:13px;color:#374151;font-style:italic;margin:0 0 8px;">
            "${c.text.slice(0, 200)}${c.text.length > 200 ? "..." : ""}"
          </p>
          <p style="font-size:12px;color:#6b7280;margin:0 0 6px;">${c.explanation}</p>
          <p style="font-size:11px;font-weight:600;color:#4f46e5;margin:0 0 4px;">SAFER ALTERNATIVE</p>
          <p style="font-size:12px;color:#374151;font-style:italic;margin:0;">${c.rewrite}</p>
        </div>
      `).join("")
    : '<p style="color:#6b7280;font-size:13px;">No high-risk clauses identified.</p>';

  const html = `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#f9fafb;margin:0;padding:32px 0;">
  <div style="max-width:600px;margin:0 auto;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.1);">

    <div style="background:#4f46e5;padding:24px 32px;">
      <p style="color:rgba(255,255,255,0.7);font-size:12px;margin:0 0 4px;text-transform:uppercase;letter-spacing:0.08em;">Contract Scanner</p>
      <h1 style="color:#fff;font-size:20px;font-weight:600;margin:0;">Your risk report is ready</h1>
    </div>

    <div style="padding:32px;">
      <p style="color:#374151;font-size:14px;margin:0 0 24px;">
        We analysed <strong>${contractTitle}</strong>. Here is your risk summary.
      </p>

      <div style="background:#f8f8fc;border-radius:10px;padding:20px 24px;margin-bottom:24px;text-align:center;">
        <p style="font-size:48px;font-weight:700;color:${scoreColor};margin:0;line-height:1;">${scan.risk_score}</p>
        <p style="font-size:13px;color:#6b7280;margin:4px 0 0;">Risk Score / 100 · Grade ${grade}</p>
      </div>

      <p style="font-size:11px;font-weight:600;color:#4f46e5;text-transform:uppercase;letter-spacing:0.06em;margin:0 0 8px;">Executive Summary</p>
      <p style="font-size:13px;color:#374151;line-height:1.6;margin:0 0 24px;">${scan.summary}</p>

      ${topClauses.length > 0 ? `
        <p style="font-size:11px;font-weight:600;color:#dc2626;text-transform:uppercase;letter-spacing:0.06em;margin:0 0 12px;">
          Top High-Risk Clauses
        </p>
        ${clauseHtml}
      ` : ""}

      <div style="margin-top:24px;padding-top:20px;border-top:1px solid #e5e7eb;">
        <p style="font-size:10px;color:#9ca3af;line-height:1.5;margin:0;">
          This report is generated by AI and is for informational purposes only. It does not constitute legal advice.
          Always consult a qualified lawyer before signing any contract.
        </p>
      </div>
    </div>
  </div>
</body>
</html>`;

  try {
    const resend = new Resend(process.env.RESEND_API_KEY);
    await resend.emails.send({
      from: "Contract Scanner <onboarding@resend.dev>",
      to: [user.email!],
      subject: `Risk Report: ${contractTitle} — Score ${scan.risk_score}/100`,
      html,
    });
    return NextResponse.json({ success: true });
  } catch (err) {
    console.error("[send-report] Resend error:", err);
    return NextResponse.json({ error: "Failed to send email" }, { status: 500 });
  }
}
